// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Inventory Management
//
//  A mini project for practice
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//  Contact: AAA http://aaa.com
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
