// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"inventory-management/models"
)

// PutUserCreatedCode is the HTTP code returned for type PutUserCreated
const PutUserCreatedCode int = 201

/*PutUserCreated User Updated

swagger:response putUserCreated
*/
type PutUserCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Users `json:"body,omitempty"`
}

// NewPutUserCreated creates PutUserCreated with default headers values
func NewPutUserCreated() *PutUserCreated {

	return &PutUserCreated{}
}

// WithPayload adds the payload to the put user created response
func (o *PutUserCreated) WithPayload(payload *models.Users) *PutUserCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user created response
func (o *PutUserCreated) SetPayload(payload *models.Users) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
