// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutUserCreatedCode is the HTTP code returned for type PutUserCreated
const PutUserCreatedCode int = 201

/*PutUserCreated updated succesfully

swagger:response putUserCreated
*/
type PutUserCreated struct {
}

// NewPutUserCreated creates PutUserCreated with default headers values
func NewPutUserCreated() *PutUserCreated {

	return &PutUserCreated{}
}

// WriteResponse to the client
func (o *PutUserCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}
