// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Item item
//
// swagger:model Item
type Item struct {

	// m r p
	// Example: 130
	MRP float64 `json:"MRP,omitempty"`

	// description
	// Example: Bru
	Description string `json:"description,omitempty"`

	// item Id
	// Example: 1
	ItemID int64 `json:"itemId,omitempty"`

	// item name
	// Example: Coffee
	ItemName string `json:"itemName,omitempty"`

	// quantity
	// Example: 6
	Quantity int64 `json:"quantity,omitempty"`

	// selling price
	// Example: 125.5
	SellingPrice float64 `json:"sellingPrice,omitempty"`
}

// Validate validates this item
func (m *Item) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this item based on context it is used
func (m *Item) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Item) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Item) UnmarshalBinary(b []byte) error {
	var res Item
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
