// Code generated by go-swagger; DO NOT EDIT.

package stock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteInventoryItemIDOKCode is the HTTP code returned for type DeleteInventoryItemIDOK
const DeleteInventoryItemIDOKCode int = 200

/*DeleteInventoryItemIDOK Item deleted

swagger:response deleteInventoryItemIdOK
*/
type DeleteInventoryItemIDOK struct {
}

// NewDeleteInventoryItemIDOK creates DeleteInventoryItemIDOK with default headers values
func NewDeleteInventoryItemIDOK() *DeleteInventoryItemIDOK {

	return &DeleteInventoryItemIDOK{}
}

// WriteResponse to the client
func (o *DeleteInventoryItemIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteInventoryItemIDNotFoundCode is the HTTP code returned for type DeleteInventoryItemIDNotFound
const DeleteInventoryItemIDNotFoundCode int = 404

/*DeleteInventoryItemIDNotFound Item not found

swagger:response deleteInventoryItemIdNotFound
*/
type DeleteInventoryItemIDNotFound struct {
}

// NewDeleteInventoryItemIDNotFound creates DeleteInventoryItemIDNotFound with default headers values
func NewDeleteInventoryItemIDNotFound() *DeleteInventoryItemIDNotFound {

	return &DeleteInventoryItemIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteInventoryItemIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
