// Code generated by go-swagger; DO NOT EDIT.

package stock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetInventorySearchItemNameParams creates a new GetInventorySearchItemNameParams object
//
// There are no default values defined in the spec.
func NewGetInventorySearchItemNameParams() GetInventorySearchItemNameParams {

	return GetInventorySearchItemNameParams{}
}

// GetInventorySearchItemNameParams contains all the bound params for the get inventory search item name operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetInventorySearchItemName
type GetInventorySearchItemNameParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	ItemName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetInventorySearchItemNameParams() beforehand.
func (o *GetInventorySearchItemNameParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rItemName, rhkItemName, _ := route.Params.GetOK("itemName")
	if err := o.bindItemName(rItemName, rhkItemName, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindItemName binds and validates parameter ItemName from path.
func (o *GetInventorySearchItemNameParams) bindItemName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ItemName = raw

	return nil
}
