// Code generated by go-swagger; DO NOT EDIT.

package stock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostInventoryCreatedCode is the HTTP code returned for type PostInventoryCreated
const PostInventoryCreatedCode int = 201

/*PostInventoryCreated Item saved successfully

swagger:response postInventoryCreated
*/
type PostInventoryCreated struct {
}

// NewPostInventoryCreated creates PostInventoryCreated with default headers values
func NewPostInventoryCreated() *PostInventoryCreated {

	return &PostInventoryCreated{}
}

// WriteResponse to the client
func (o *PostInventoryCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}
